displayName=Rune Party Showdown
author=Tree Twunk
build=standard
description=A party-style board game packed with minigames.
tags=game,event,party,board,dice,minigame,showdown,rune
plugins=gay.runescape.runeparty.RunePartyPlugin
